"""导入本包会把全部表注册到 ``Base.metadata``。"""

from fcc_api.db.models.audit import AuditAction, AuditEvent, AuditScope
from fcc_api.db.models.cases import (
    AccountFeature,
    Case,
    CaseReferenceCounter,
    CaseStatus,
    EntityType,
    TaxResidency,
)
from fcc_api.db.models.checklist import ChecklistItem, CustomRequirement, DocStatus
from fcc_api.db.models.documents import (
    CaseDocument,
    CdrStatus,
    ExtractionStatus,
    RelationStatus,
    ScanStatus,
    StorageState,
    UploadSlot,
    UploadSlotStatus,
)
from fcc_api.db.models.launch import (
    AiSuggestion,
    ApprovalStatus,
    AuditOutbox,
    DeletionJob,
    DeletionJobStatus,
    DocumentEntity,
    DocumentEntityKind,
    DocumentRelation,
    LegalHold,
    LegalHoldScope,
    PortalInvite,
    RelationType,
    RuleApproval,
    ScreeningDisposition,
    ScreeningRun,
    ScreeningStatus,
    Submission,
    SubmissionStatus,
    SubmissionTarget,
    SuggestionKind,
    SuggestionStage,
)
from fcc_api.db.models.extractions import (
    DocumentExtraction,
    ExtractionField,
    ExtractionPage,
    ExtractionRunStatus,
)
from fcc_api.db.models.parties import Party, PartyKind, UsTaxClass
from fcc_api.db.models.rules import (
    RuleDraft,
    RuleDraftStatus,
    RuleLibraryState,
    RuleVersion,
    RuleVersionKind,
)
from fcc_api.db.models.tasks import ReviewTask, TaskSource
from fcc_api.db.models.users import Role, User

__all__ = [
    "AccountFeature",
    "AiSuggestion",
    "ApprovalStatus",
    "AuditAction",
    "AuditEvent",
    "AuditOutbox",
    "AuditScope",
    "Case",
    "CaseDocument",
    "CaseReferenceCounter",
    "CaseStatus",
    "CdrStatus",
    "ChecklistItem",
    "CustomRequirement",
    "DeletionJob",
    "DeletionJobStatus",
    "DocStatus",
    "DocumentEntity",
    "DocumentEntityKind",
    "DocumentExtraction",
    "DocumentRelation",
    "EntityType",
    "ExtractionField",
    "ExtractionPage",
    "ExtractionRunStatus",
    "ExtractionStatus",
    "LegalHold",
    "LegalHoldScope",
    "Party",
    "PartyKind",
    "PortalInvite",
    "RelationStatus",
    "RelationType",
    "ReviewTask",
    "Role",
    "RuleApproval",
    "RuleDraft",
    "RuleDraftStatus",
    "RuleLibraryState",
    "RuleVersion",
    "RuleVersionKind",
    "ScanStatus",
    "ScreeningDisposition",
    "ScreeningRun",
    "ScreeningStatus",
    "StorageState",
    "Submission",
    "SubmissionStatus",
    "SubmissionTarget",
    "SuggestionKind",
    "SuggestionStage",
    "TaskSource",
    "TaxResidency",
    "UploadSlot",
    "UploadSlotStatus",
    "UsTaxClass",
    "User",
]
